DELIMITER //

CREATE OR REPLACE PROCEDURE TESTMS.sp_Return_USERS()
BEGIN
    SELECT
        U.UID,
        U.NAME
    FROM t_Users U;

#     SIGNAL SQLSTATE '45000'
# 		SET MESSAGE_TEXT = 'TEST';
END //

DELIMITER ;